### PR TITLE
Feat/aggr stats matplot

### LINKED ISSUE #95: Plot aggregate statistics with matplot
Use ColorMaps

### PR DESCRIPTION
**Pull request by MaxStroh**
Use matplotlib to plot all aggregate statistics plots.
refactored methods to more generalized method, so we can now easily add timeperiod columns (e.g. day of week) and we will get a whole aggregate statistics plot of the same design.

### CODE REVIEW

**Comment by MaxStroh** [comment]
Aggregate_Statistics_Day_of_week_start

**Review by weisske — APPROVED** [review]
Very nice work.
totally approved!!!

**Review by Speedfan94 — APPROVED** [review]
important additions

**Comment by weisske** [comment]
Also viewed in live session together!

**Review by mulko93 — APPROVED** [review]
great vizualizations!

**Pull request merged**
